// <auto-generated />
using System;
using IT_Service_Management_System.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_Service_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630084900_UpgradeTicketModel")]
    partial class UpgradeTicketModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT_Service_Management_System.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ActivityCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ActivityCategories");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.AppConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertEmailRecipients")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("AlertOnBackupFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnDatabaseFailure")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnLargeDataExport")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnMultipleFailedLogins")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnNewAdminAccount")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnPrivilegeEscalation")
                        .HasColumnType("bit");

                    b.Property<bool>("AlertOnSuspiciousLocation")
                        .HasColumnType("bit");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("BackupFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BackupPath")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("BackupRetentionCount")
                        .HasColumnType("int");

                    b.Property<string>("BackupTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("LockoutDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("LockoutMaxFailedAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MfaOtpValidityMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("MfaRequiredForAdmins")
                        .HasColumnType("bit");

                    b.Property<int>("PasswordExpiryDays")
                        .HasColumnType("int");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordRequireDigit")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireSpecial")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireUppercase")
                        .HasColumnType("bit");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SessionIdleTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpServer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PurchaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ClearanceWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ExitClearanceId");

                    b.ToTable("ClearanceWorkflows");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HodId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HodId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.DevelopmentClearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BitbucketAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BitbucketDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BitbucketReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClearedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<string>("ManageEngineAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ManageEngineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManageEngineReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectManagementAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectManagementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectManagementReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentClearances");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.EngagementStayInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BSCSystemComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BSCSystemRating")
                        .HasColumnType("int");

                    b.Property<string>("CareerOpportunitiesComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CareerOpportunitiesRating")
                        .HasColumnType("int");

                    b.Property<string>("ChangesToWorkingAtAxis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunicationChannelsComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommunicationChannelsRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentPositionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentPrioritiesAndOverallWellbeing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateJoinedAxis")
                        .HasColumnType("datetime2");

                    b.Property<string>("DemotivatingFactors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentOpportunitiesComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DevelopmentOpportunitiesRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiscussionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FeelsSupported")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasDevelopmentPlan")
                        .HasColumnType("bit");

                    b.Property<string>("ImprovementIdeas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewerOverallComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobSatisfactionComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobSatisfactionRating")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadershipQualityComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadershipQualityRating")
                        .HasColumnType("int");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerRelationshipComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerRelationshipRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivationAndEngagementFactors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAndSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextCareerMilestone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationGeneralComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationGeneralRating")
                        .HasColumnType("int");

                    b.Property<string>("OtherComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OtherRating")
                        .HasColumnType("int");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("int");

                    b.Property<string>("PayAndBenefitsComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayAndBenefitsRating")
                        .HasColumnType("int");

                    b.Property<string>("ReasonsPeopleLeave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonsPeopleStay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RewardForPerformanceComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardForPerformanceRating")
                        .HasColumnType("int");

                    b.Property<string>("SkillsUtilizationFeedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamRelationshipComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamRelationshipRating")
                        .HasColumnType("int");

                    b.Property<string>("WellbeingComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WellbeingRating")
                        .HasColumnType("int");

                    b.Property<string>("WorkingConditionsComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingConditionsRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EngagementStayInterviews");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitClearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmployeeSubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ExitClearances");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitClearanceEmployeeDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfNotice")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<string>("ForwardingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDayOfWork")
                        .HasColumnType("datetime2");

                    b.Property<string>("LengthOfService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionHeld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExitClearanceId");

                    b.ToTable("ExitClearanceEmployeeDetails");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AdequateTrainingAndResources")
                        .HasColumnType("bit");

                    b.Property<int>("CareerGrowthOpportunities")
                        .HasColumnType("int");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunicationCollaborationSuggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyCultureWorkEnvironment")
                        .HasColumnType("int");

                    b.Property<int>("CompensationAndBenefits")
                        .HasColumnType("int");

                    b.Property<string>("CompensationMarketCompetitiveness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CultureImprovementSuggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfResignation")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeRetentionRecommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FeltValuedAndRecognized")
                        .HasColumnType("bit");

                    b.Property<string>("HRRepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewConductedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobResponsibilities")
                        .HasColumnType("int");

                    b.Property<string>("JobSatisfactionComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastWorkingDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManagementLeadershipStyle")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MostLikedAboutCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OtherRating")
                        .HasColumnType("int");

                    b.Property<string>("OtherReasonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryReasonForDeparture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipWithManagerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelationshipWithManagerRating")
                        .HasColumnType("int");

                    b.Property<string>("ResignationPreventionSuggestions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ResponsibilitiesClearlyDefined")
                        .HasColumnType("bit");

                    b.Property<bool?>("RoleMetExpectations")
                        .HasColumnType("bit");

                    b.Property<bool?>("SatisfiedWithSalaryAndBenefits")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SignOffDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SupportedByTeamAndLeadership")
                        .HasColumnType("bit");

                    b.Property<string>("WorkLifeBalanceComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkLifeBalanceRating")
                        .HasColumnType("int");

                    b.Property<bool?>("WouldRecommendCompany")
                        .HasColumnType("bit");

                    b.Property<bool?>("WouldReturnToCompany")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ExitInterviews");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.FinanceClearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClearedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalDuesDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalDuesReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalDuesReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReceiptsDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptsReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptsReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StaffAdvanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffAdvanceReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffAdvanceReference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinanceClearances");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.HodApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HandoverDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandoverSignature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HodApprovals");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.HrApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<bool>("ExitInterviewCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExitInterviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitInterviewReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FuneralPolicyCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FuneralPolicyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuneralPolicyReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HandoverReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandoverReportReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HandoverReportSubmitted")
                        .HasColumnType("bit");

                    b.Property<bool>("MedicalAidCancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MedicalAidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalAidReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NSSACancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NSSADate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NSSAReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResignationLetterDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ResignationLetterReceived")
                        .HasColumnType("bit");

                    b.Property<string>("ResignationLetterReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StaffIdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffIdReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StaffIdReturned")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HrApprovals");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartsReplaced")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareInstalled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentScheduleId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.PaymentSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Departments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextRunDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentSchedules");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.SSLCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRenewed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRenewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SSLCertificates");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.StockHandoverItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockHandoverItems");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.SupervisorApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SupervisorApprovals");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.SystemsAdminClearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessRemovalAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccessRemovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessRemovalReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccessoriesAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AccessoriesDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccessoriesReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClearedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndpointSecurityAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndpointSecurityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndpointSecurityReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExitClearanceId")
                        .HasColumnType("int");

                    b.Property<string>("LaptopAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaptopBagAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LaptopBagDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaptopBagReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LaptopDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaptopReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockerAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockerReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialMediaAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SocialMediaDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SocialMediaReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SophosAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SophosDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SophosReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemsAdminClearances");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentDevelopmentAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DevelopmentAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TalentIdentificationId")
                        .HasColumnType("int");

                    b.Property<string>("Timeline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TalentIdentificationId");

                    b.ToTable("TalentDevelopmentActions");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentDirectReportAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRating")
                        .HasColumnType("int");

                    b.Property<int>("TalentIdentificationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TalentIdentificationId");

                    b.ToTable("TalentDirectReportAssessments");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentIdentification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanOccupyHigherGrade")
                        .HasColumnType("bit");

                    b.Property<string>("CareerAspirations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengesApplyingAxisValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CourageConvictions")
                        .HasColumnType("bit");

                    b.Property<bool>("CourageRiskTaking")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliverySetbacks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KPI2023")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KPI2024")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KPI2025")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KPI2026")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyProjectsLed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadershipDevelopmentAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeadershipOverallComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LearningAgility")
                        .HasColumnType("bit");

                    b.Property<string>("LongTermBusinessInitiatives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mobility")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextCareerMilestone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NineBoxAssessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OpenToFeedback")
                        .HasColumnType("bit");

                    b.Property<int>("Readiness")
                        .HasColumnType("int");

                    b.Property<bool>("Resilience")
                        .HasColumnType("bit");

                    b.Property<int>("RiskOfLeaving")
                        .HasColumnType("int");

                    b.Property<bool>("SelfAwareness")
                        .HasColumnType("bit");

                    b.Property<string>("SelfDevelopmentActions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelfInitiatedLeadershipDevelopment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StructuredOneOnOnes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamCapabilityDevelopment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminatedPoorPerformers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThinkingComplexity")
                        .HasColumnType("bit");

                    b.Property<bool>("ThinkingJudgement")
                        .HasColumnType("bit");

                    b.Property<bool>("ThinkingScale")
                        .HasColumnType("bit");

                    b.Property<bool>("WillingToImprove")
                        .HasColumnType("bit");

                    b.Property<bool>("WisdomFastJudgement")
                        .HasColumnType("bit");

                    b.Property<bool>("WisdomLongTermImpact")
                        .HasColumnType("bit");

                    b.Property<bool>("WisdomWhenToAct")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TalentIdentifications");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FirstRespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TicketAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketMessageId");

                    b.ToTable("TicketAttachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachment_Owner", "[TicketId] IS NOT NULL OR [TicketMessageId] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MfaOtpCodeHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MfaOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserAccessRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductionServerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemsAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionReleaseNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccessRights");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserAccessRightItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountManagement")
                        .HasColumnType("bit");

                    b.Property<bool>("Approval")
                        .HasColumnType("bit");

                    b.Property<bool>("Confirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("Initiate")
                        .HasColumnType("bit");

                    b.Property<bool>("Reports")
                        .HasColumnType("bit");

                    b.Property<int>("UserAccessRightsId")
                        .HasColumnType("int");

                    b.Property<bool>("UserManagement")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserAccessRightsId");

                    b.ToTable("UserAccessRightItems");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Activity", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.ActivityCategory", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Asset", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.AssetHistory", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.Asset", "Asset")
                        .WithMany("History")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IT_Service_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ClearanceWorkflow", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IT_Service_Management_System.Models.ExitClearance", "ExitClearance")
                        .WithMany("Workflows")
                        .HasForeignKey("ExitClearanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("ExitClearance");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Department", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "Hod")
                        .WithMany()
                        .HasForeignKey("HodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Hod");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitClearance", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitClearanceEmployeeDetails", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.ExitClearance", "ExitClearance")
                        .WithMany()
                        .HasForeignKey("ExitClearanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExitClearance");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Payment", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.PaymentSchedule", "PaymentSchedule")
                        .WithMany()
                        .HasForeignKey("PaymentScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentSchedule");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentDevelopmentAction", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.TalentIdentification", "TalentIdentification")
                        .WithMany("DevelopmentActions")
                        .HasForeignKey("TalentIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentIdentification");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentDirectReportAssessment", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.TalentIdentification", "TalentIdentification")
                        .WithMany("DirectReports")
                        .HasForeignKey("TalentIdentificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentIdentification");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Ticket", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IT_Service_Management_System.Models.User", "CreatedBy")
                        .WithMany("TicketsCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TicketAttachment", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IT_Service_Management_System.Models.TicketMessage", "TicketMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ticket");

                    b.Navigation("TicketMessage");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TicketMessage", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IT_Service_Management_System.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.User", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IT_Service_Management_System.Models.User", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserAccessRightItem", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.UserAccessRight", "UserAccessRight")
                        .WithMany("Users")
                        .HasForeignKey("UserAccessRightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccessRight");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserSession", b =>
                {
                    b.HasOne("IT_Service_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ActivityCategory", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Asset", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.ExitClearance", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TalentIdentification", b =>
                {
                    b.Navigation("DevelopmentActions");

                    b.Navigation("DirectReports");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.TicketMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Messages");

                    b.Navigation("Subordinates");

                    b.Navigation("TicketsCreated");
                });

            modelBuilder.Entity("IT_Service_Management_System.Models.UserAccessRight", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
